### PR TITLE
Refactor pin hierarchy to avoid multiple classes for same boards

### PR DESCRIPTION
**Pull request by dionisiydk**
Hierachy of pin functions is extracted from pin hierarchy:
- PotPWMFunction, PotI2CFunction, ..
- single PotGPIO class which contains an instance of function.

Number property is removed from pins. There is only id - hardware producer identificator of pin (BCM in case of Raspberry).
Pinout inspector is modified according to this change. Now name of pin is #gpio+id. And the id column is removed because it is part of the name. Another column Function is added to show PWM, I2C and etc.:

modifiedBoardInspector

The Flient API is introduced to create gpio's and reference them out of board:
```Smalltalk
12 gpio 
```
To create a pin with id=12 (BCM in case of RPI)
```Smalltalk
12 gpio: PotPWMFunction 
```
To create a gpio with concrete function.
```Smalltalk
3.3 powerPin.
5 powerPin.
0 powerPin.
```
To create enegry pins. Last expression retuns ground pin.
The initialization of all boards are modified and simplified with this DSL.

Pin references are introduced:
```Smalltalk
23 gpioHeader
```
To get a reference to pin at 23-th physical position on the board in default (first) connector. Devices can be created with pin references. When they are installed into the board references are replaced by actual pin instances.
```Smalltalk
(23@2) gpioHeader
```
To reference gpio at 2-th column and 23-th row in default (first) connector
```Smalltalk
23 gpioHeader @ #P5
```
To reference a pin in concrete connector (#P5).

### CODE REVIEW

**Comment by dionisiydk** [comment]
@oliveiraallex The PR is not completed yet. But board inspectors are done.
Please review and tell me what you think.

**Comment by oliveiraallex** [comment]
> @oliveiraallex The PR is not completed yet. But board inspectors are done.
> Please review and tell me what you think.

Hi @dionisiydk, cool! I liked so much this approach. This simplifies what the developer needs to know about the gpio numbers and ids, and avoid some confusion with bcm and wiringpi numbers. 
I did some tests (dummy) and looks nice:
image
Next week I will test it in the Rasp. 

I didn't understand the part "23 gpioHeader".
In that PR (https://github.com/pharo-iot/PharoThings/pull/28/commits/e3b638529e925f07ce1700942417676f43c0c3e5 ), I was calling the instance of pins using the header number. I could use `led := pinAtHeader: 23` if I didn't know the number of gpio, but I tried the new way `led := 23 gpioHeader` and didn't work.

**Comment by dionisiydk** [comment]
> I didn't understand the part "23 gpioHeader".
> In that PR ([e3b6385](https://github.com/pharo-iot/PharoThings/commit/e3b638529e925f07ce1700942417676f43c0c3e5) ), I was calling the instance of pins using the header number. I could use `led := pinAtHeader: 23` if I didn't know the number of gpio, but I tried the new way `led := 23 gpioHeader` and didn't work.

Yes. That's idea. I just did not finish integration with these pin references.
So ultrasonic will be:
```
ultrasonic := PotHCSR04Device triggerPin: 23 gpioHeader echoPin: 18 gpioHeader
```
And you will not need to manually perform #pinAtHeader: inside. It will be done during #installDevice:.

**Comment by dionisiydk** [comment]
So I done last changes.
It includes more tests.
And now every device must implement extra method #peripherals to return all configured pins and devices. Before this method was not abstract and only used in UI. Now it is important to require it because it is used to sync installed device with actual board pins.

**Comment by oliveiraallex** [comment]
> So I done last changes.
> It includes more tests.
> And now every device must implement extra method #peripherals to return all configured pins and devices. Before this method was not abstract and only used in UI. Now it is important to require it because it is used to sync installed device with actual board pins.

Nice, I did some tests and it's working. With this new approach is more understandable and easy to work with PharoThings. I will merge it and include this method in the LCD and Ultrasonic devices. Thanks a lot @dionisiydk

**Pull request merged**
