### PR TITLE
Add double dispatch to boards to support configure devices

### PR DESCRIPTION
**Pull request by oliveiraallex**
Add double dispatch to boards to support configure devices

### CODE REVIEW

**Comment by dionisiydk** [comment]
After discussion about LCDs I more inclined that there is no need for such configuration methods. There are no real physical logic behind them. 
If user anyway needs to physically plug devices to concrete pins what the value default pins give to user? 

For example in Ultrasonic sensor you decided that default triggerPin is 5 and echoPin is 17. How user will know it and why he need to know it?
Maybe you want to have simplest working example like 
```Smalltalk 
UltrasonicDevice new readValue
```
But is it really make sense to have? For real scenarios users need to know how to choose pins by themselves. And you will anyway need to explain this and show something like
```Smalltalk
UltrasonicDevice triggerPin: 5 echoPin: 17.
```

**Comment by miapharo** [comment]
How do I do that?

**Comment by dionisiydk** [comment]
I think with latest changes we don't need this logic.
Default configuration don't needs to depend on type of board. It is just kind of example: we create device using #new, install it to the board and inspector shows where wires need to be plugged in real.
So it can be initialized in #initialize method of device using gpioHeader's approach. 

For simple devices with couple of pins it looks a bit redundant. But maybe it is a good idea to have it everywhere. In any case it is important to provide API for every device to create it with custom pins.

**Comment by oliveiraallex** [comment]
> I think with latest changes we don't need this logic.
> Default configuration don't needs to depend on type of board. It is just kind of example: we create device using #new, install it to the board and inspector shows where wires need to be plugged in real.
> So it can be initialized in #initialize method of device using gpioHeader's approach.
> 
> For simple devices with couple of pins it looks a bit redundant. But maybe it is a good idea to have it everywhere. In any case it is important to provide API for every device to create it with custom pins.

Yes, I think is a bit redundant now (in the ultrasonic sensor, for example, I ignored this). But I think we can leave this option, just to provide a better API. Can I merge it?

**Comment by dionisiydk** [comment]
I don't think this option is good in current state. Just remember that when you start adopt ultrasonic you put in configure method gpioHeaders and sync logic was not working in that case (because it is performed before #configure.. call). It could cause confusion.

I think the better would be to introduce method configureDefaultPeripherals (or maybe better name it #configureExamplePeripherals) and simply call it from the initialize:
```Smalltalk
PotDevice>>initialize
   super initialize.
   self configureExamplePeripherals

PotDevice>>configureExamplePeripherals
   "Subclasses can provide example configuration of pin variables.
   So users will be able simply create device using #new (PotLCD new)
   and see in the board inspector how to connect it in the real world (with real wires)"
```

**Comment by dionisiydk** [comment]
And it can be closed?

**Comment by oliveiraallex** [comment]
> And it can be closed?

Yes. It was solved in the PR 27 https://github.com/pharo-iot/PharoThings/pull/27 
Thanks

**Pull request closed without merging**
